language: generic
sudo: required
services:
  - docker
before_install: 
  - docker build -t docker-ci-aws -f Dockerfile.dev .
script:
  - docker run -e CI=true docker-ci-aws npm run test
deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
  region: 'us-east-1'
  app: 'my-test-app'
  env: 'Mytestapp-env'
  bucket_name: 'elasticbeanstalk-us-east-1-052670018888'
  bucket_path: 'my-test-app'
  on:
    branch: master
